# ============================================================
# SocialHomes.Ai — Staging CI/CD Pipeline (Cloud Build)
# Triggers on push to any branch except main (PRs).
# Deploys to socialhomes-staging Cloud Run service.
# ============================================================

substitutions:
  _REGION: europe-west2
  _SERVICE_NAME: socialhomes-staging
  _REGISTRY: europe-west2-docker.pkg.dev/$PROJECT_ID/socialhomes/app-staging
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '3'
  _MEMORY: '512Mi'
  _CPU: '1'

steps:
  # ── Step 1: Build Docker image ──
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args:
      - 'build'
      - '-t'
      - '${_REGISTRY}:$COMMIT_SHA'
      - '-t'
      - '${_REGISTRY}:$BRANCH_NAME'
      - '--cache-from'
      - '${_REGISTRY}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'

  # ── Step 2: Smoke test inside built image ──
  - name: '${_REGISTRY}:$COMMIT_SHA'
    id: test
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "=== Staging smoke test ==="
        node server/dist/index.js &
        SERVER_PID=$$!
        sleep 3
        curl -sf http://localhost:8080/health | grep -q '"status"' && echo "✓ Health check passed" || (echo "✗ Health check failed" && exit 1)
        kill $$SERVER_PID 2>/dev/null || true
    env:
      - 'NODE_ENV=test'
      - 'PORT=8080'
    waitFor: ['build']

  # ── Step 3: Push Docker image ──
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args:
      - 'push'
      - '${_REGISTRY}:$COMMIT_SHA'
    waitFor: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    id: push-branch
    args:
      - 'push'
      - '${_REGISTRY}:$BRANCH_NAME'
    waitFor: ['test']

  # ── Step 4: Deploy to Cloud Run (Staging) ──
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGISTRY}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=staging'
      - '--update-secrets'
      - 'FIREBASE_API_KEY=FIREBASE_API_KEY:latest,FIREBASE_AUTH_DOMAIN=FIREBASE_AUTH_DOMAIN:latest,FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest,DEMO_USER_PASSWORD=DEMO_USER_PASSWORD:latest'
      - '--labels'
      - 'app=socialhomes,env=staging,managed-by=cloudbuild'
      - '--tag'
      - 'pr-$SHORT_SHA'
    waitFor: ['push']

  # ── Step 5: Output staging URL ──
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: output-url
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} --format='value(status.url)')
        echo "======================================"
        echo "  Staging deployed: $${SERVICE_URL}"
        echo "======================================"
    waitFor: ['deploy']

images:
  - '${_REGISTRY}:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

timeout: 900s
